-- Flect — 60 Days of Prompts
-- Run this in Supabase SQL Editor → New query → Run
-- Starts from today (March 31, 2026) and goes forward 60 days

INSERT INTO public.prompts (prompt_date, text, category) VALUES
  (current_date + 0,  'What made you pause and look twice today?', 'mindfulness'),
  (current_date + 1,  'Capture something that feels like home.', 'authenticity'),
  (current_date + 2,  'Find a color that matches your mood right now.', 'mood'),
  (current_date + 3,  'What are you looking forward to this week?', 'joy'),
  (current_date + 4,  'Show something you made or created recently.', 'creative'),
  (current_date + 5,  'Photograph the light in your space right now.', 'mindfulness'),
  (current_date + 6,  'What does rest look like for you today?', 'lifestyle'),
  (current_date + 7,  'Find beauty in something you usually overlook.', 'mindfulness'),
  (current_date + 8,  'Capture a texture that caught your attention.', 'creative'),
  (current_date + 9,  'What small thing brought you comfort today?', 'gratitude'),
  (current_date + 10, 'Show where you do your best thinking.', 'authenticity'),
  (current_date + 11, 'What does your morning look like right now?', 'lifestyle'),
  (current_date + 12, 'Capture something that feels like spring.', 'joy'),
  (current_date + 13, 'What are you holding onto that you should let go?', 'mood'),
  (current_date + 14, 'Photograph something that has a good story behind it.', 'authenticity'),
  (current_date + 15, 'Find order in something chaotic, or chaos in something ordered.', 'creative'),
  (current_date + 16, 'What does your energy feel like today?', 'mood'),
  (current_date + 17, 'Show something that made you smile this week.', 'joy'),
  (current_date + 18, 'Capture a shadow or reflection that caught your eye.', 'creative'),
  (current_date + 19, 'What are you grateful for that you rarely mention?', 'gratitude'),
  (current_date + 20, 'Show your favorite corner of wherever you are.', 'authenticity'),
  (current_date + 21, 'What does a slow moment look like today?', 'mindfulness'),
  (current_date + 22, 'Capture something that is ending or beginning.', 'mood'),
  (current_date + 23, 'What simple thing do you do every day without thinking?', 'lifestyle'),
  (current_date + 24, 'Show something that represents who you are right now.', 'authenticity'),
  (current_date + 25, 'Find something small that is actually extraordinary.', 'mindfulness'),
  (current_date + 26, 'What does your creative process look like today?', 'creative'),
  (current_date + 27, 'Capture a moment of stillness.', 'mindfulness'),
  (current_date + 28, 'What song would be the soundtrack to today?', 'mood'),
  (current_date + 29, 'Show something you have been meaning to fix or finish.', 'lifestyle'),
  (current_date + 30, 'What does growth look like in your life right now?', 'joy'),
  (current_date + 31, 'Capture something weathered, worn, or well-loved.', 'authenticity'),
  (current_date + 32, 'What boundary are you proud of keeping lately?', 'mood'),
  (current_date + 33, 'Show the view from where you spend most of your time.', 'lifestyle'),
  (current_date + 34, 'Find something that represents a fresh start.', 'joy'),
  (current_date + 35, 'Capture a pattern in nature or your environment.', 'creative'),
  (current_date + 36, 'What are you learning right now?', 'authenticity'),
  (current_date + 37, 'Show something that requires patience.', 'mindfulness'),
  (current_date + 38, 'What does your ideal version of today look like?', 'mood'),
  (current_date + 39, 'Capture something that connects you to someone you love.', 'gratitude'),
  (current_date + 40, 'Show a before and after — anything counts.', 'creative'),
  (current_date + 41, 'What does abundance look like in your life?', 'gratitude'),
  (current_date + 42, 'Find something that has been there all along.', 'mindfulness'),
  (current_date + 43, 'Capture the last hour of daylight today.', 'lifestyle'),
  (current_date + 44, 'What are you most curious about right now?', 'joy'),
  (current_date + 45, 'Show something that takes up space in your mind lately.', 'mood'),
  (current_date + 46, 'Capture something that smells like a memory.', 'authenticity'),
  (current_date + 47, 'What does being kind to yourself look like today?', 'gratitude'),
  (current_date + 48, 'Show something you built, fixed, or figured out.', 'creative'),
  (current_date + 49, 'Find the most interesting thing within arm''s reach.', 'mindfulness'),
  (current_date + 50, 'What does your body need more of right now?', 'lifestyle'),
  (current_date + 51, 'Capture something that changed your perspective recently.', 'mood'),
  (current_date + 52, 'Show a place that feels sacred or special to you.', 'authenticity'),
  (current_date + 53, 'What are you celebrating, no matter how small?', 'joy'),
  (current_date + 54, 'Find something that reminds you of a different time.', 'gratitude'),
  (current_date + 55, 'Capture movement — anything in motion.', 'creative'),
  (current_date + 56, 'What does your version of peace look like?', 'mindfulness'),
  (current_date + 57, 'Show something you are proud of this month.', 'joy'),
  (current_date + 58, 'What does the end of the day feel like today?', 'mood'),
  (current_date + 59, 'Capture something that makes ordinary life feel remarkable.', 'gratitude')
ON CONFLICT (prompt_date) DO NOTHING;
